server:
  port: 8088

spring:
  application:
    name: eureka-zuul

zuul:
  #路由前缀
  prefix: /api
  #声明路由
  routes:
    xxx-service: /manage/**
    search-server: /search/**
    user-server: /user-center/**
    oauth-server: /oauth/**
    car-server: /car/**
    order-server: /order/**
    pay-server: /pay/**
    comments-service: /commment/**
    miaosha-service: /miaosha/**
#  # 声明路由
#  routes:
#    # 路由名称
#    api-xxx:
#      # 声明将所有以/api-ribbon/的请求都转发到eureka-ribbon的服务中
#      path: /api-xxx/**
#      serviceId: xxx-service
#    api-search:
#      path: /api-search/**
#      serviceId: search-server

  # 启用重试
  retryable: true
  # 包含此路径的不进行路由
  ignored-patterns: /upload/**
  # 忽略上传服务
  ignored-services:
    -upload-server
  #zuul默认不会将域名加入到header中  默认值为false
  add-host-header: true
  #set-cookie 方法被zuul禁止了，将这个属性设置为空，代表启用set-cookie方法
  sensitive-headers:

mrshop:
  #声明不进行拦截的请求用,分隔
  filter:
    excludes: /api/oauth/oauth/login,/api/user-center/user/register,/api/search/es/search,/api/oauth/oauth/verify,/api/car/car/getUserGoodsCar,/api/order/order/createOrder,/api/pay/pay/requestPay,/api/car/car/addCar,/api/order/save/saveAddrInfo,/api/order/search/getAddrInfo,/api/order/search/getAddrInfoById,/api/order/delete/removeAddrInfoById,/api/manage/good/getSpuInfo,/api/manage/brand/getBrandInfo,/api/manage/good/getSpuInfo,/api/manage/category/list,/api/manage/specparam/getSpecParamInfo
  jwt:
    pubKeyPath: D:\images\rea.pub # 公钥地址(私钥加密,公钥解密)
    cookieName: MRSHOP_TOKEN

#配置负载
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 13500 # 熔断超时时长：6000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/